name: Deploy to AWS
env:
   EB_PACKAGE_S3_BUCKET_NAME: "Eshopbackend"
   EB_ENVIRONMENT_NAME: "Eshopbackend"
   EB_APPLICATION_NAME: "Eshop"
   AWS_REGION_NAME: "us-east-1"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copy deployment package to S3 bucket
        run: aws s3 cp ${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/ "${{ env.EB_ENVIRONMENT_NAME }}/${{ github.sha }}.zip"

      - name: Create new Elastic Beanstalk application version
        run: aws elasticbeanstalk create-application-version \
             --application-name ${{ env.EB_APPLICATION_NAME }} \
             --version-label "Ver-${{ github.sha }}" \
             --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.EB_ENVIRONMENT_NAME }}/${{ github.sha }}.zip"

      - name: Deploy new application version to Elastic Beanstalk environment
        run: aws elasticbeanstalk update-environment \
             --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
             --version-label "Ver-${{ github.sha }}"
